// @ts-check
/**
 * iconNames.js -- a CURATED static list of common Material icon names.
 *
 * This list exists so the editor (icon picker + autocomplete) can offer a
 * sensible set of icon suggestions WITHOUT importing `@mui/icons-material`,
 * which is enormous (thousands of components) and would bloat the bundle. The
 * wiremark renderer accepts any icon name "forgivingly spelled" and degrades
 * unknown names to a placeholder, so this list is purely a convenience for
 * suggestions -- it does not need to be exhaustive.
 *
 * Names are the canonical MUI PascalCase identifiers (e.g. `ChevronRight`).
 */

/**
 * @type {readonly string[]}
 */
export const ICON_NAMES = Object.freeze([
  // Navigation / chrome
  'Menu',
  'MenuOpen',
  'Close',
  'MoreVert',
  'MoreHoriz',
  'ArrowBack',
  'ArrowForward',
  'ArrowUpward',
  'ArrowDownward',
  'ArrowDropDown',
  'ArrowDropUp',
  'ArrowLeft',
  'ArrowRight',
  'ChevronLeft',
  'ChevronRight',
  'ExpandLess',
  'ExpandMore',
  'UnfoldMore',
  'UnfoldLess',
  'FirstPage',
  'LastPage',
  'KeyboardArrowUp',
  'KeyboardArrowDown',
  'KeyboardArrowLeft',
  'KeyboardArrowRight',
  'NavigateBefore',
  'NavigateNext',
  'Home',
  'Dashboard',
  'Apps',
  'Widgets',
  'ViewAgenda',
  'ViewList',
  'ViewModule',
  'ViewColumn',
  'ViewQuilt',
  'ViewComfy',
  'GridView',
  'TableRows',
  'Article',
  'Subject',

  // Actions
  'Search',
  'SearchOff',
  'Add',
  'AddCircle',
  'AddCircleOutline',
  'AddBox',
  'Remove',
  'RemoveCircle',
  'RemoveCircleOutline',
  'Edit',
  'EditOff',
  'ModeEdit',
  'Create',
  'Delete',
  'DeleteForever',
  'DeleteOutline',
  'Save',
  'SaveAlt',
  'SaveAs',
  'Cancel',
  'Done',
  'DoneAll',
  'Check',
  'CheckCircle',
  'CheckCircleOutline',
  'CheckBox',
  'CheckBoxOutlineBlank',
  'IndeterminateCheckBox',
  'RadioButtonChecked',
  'RadioButtonUnchecked',
  'Clear',
  'ClearAll',
  'Undo',
  'Redo',
  'Refresh',
  'Sync',
  'Autorenew',
  'Cached',
  'Restore',
  'History',
  'Update',
  'ContentCopy',
  'ContentCut',
  'ContentPaste',
  'FileCopy',
  'Download',
  'Upload',
  'CloudUpload',
  'CloudDownload',
  'CloudDone',
  'CloudOff',
  'Print',
  'Share',
  'Send',
  'Reply',
  'ReplyAll',
  'Forward',
  'Launch',
  'OpenInNew',
  'OpenInFull',
  'CloseFullscreen',
  'OpenInBrowser',
  'ExitToApp',
  'Login',
  'Logout',
  'Link',
  'LinkOff',
  'AttachFile',
  'Attachment',
  'Filter',
  'FilterList',
  'FilterAlt',
  'Sort',
  'Tune',
  'Search',
  'ZoomIn',
  'ZoomOut',
  'Fullscreen',
  'FullscreenExit',
  'DragHandle',
  'DragIndicator',
  'OpenWith',
  'ImportExport',
  'SwapHoriz',
  'SwapVert',

  // Files / documents
  'Folder',
  'FolderOpen',
  'FolderShared',
  'CreateNewFolder',
  'InsertDriveFile',
  'Description',
  'TextSnippet',
  'NoteAdd',
  'Note',
  'Notes',
  'Assignment',
  'Book',
  'MenuBook',
  'LibraryBooks',
  'Bookmark',
  'BookmarkBorder',
  'Bookmarks',
  'Label',
  'LabelImportant',
  'Image',
  'ImageNotSupported',
  'Photo',
  'PhotoCamera',
  'Collections',
  'PictureAsPdf',
  'Code',
  'IntegrationInstructions',
  'Terminal',
  'DataObject',

  // Communication
  'Email',
  'MarkEmailRead',
  'MarkEmailUnread',
  'Drafts',
  'Inbox',
  'Outbox',
  'Send',
  'Chat',
  'ChatBubble',
  'ChatBubbleOutline',
  'Comment',
  'Message',
  'Forum',
  'QuestionAnswer',
  'Sms',
  'Call',
  'Phone',
  'PhoneInTalk',
  'Contacts',
  'ContactMail',
  'ContactPhone',
  'Notifications',
  'NotificationsActive',
  'NotificationsNone',
  'NotificationsOff',

  // People / account
  'Person',
  'PersonAdd',
  'PersonRemove',
  'PersonOutline',
  'People',
  'PeopleAlt',
  'Group',
  'GroupAdd',
  'AccountCircle',
  'AccountBox',
  'SupervisorAccount',
  'ManageAccounts',
  'Badge',
  'Face',
  'EmojiPeople',

  // Status / feedback
  'Info',
  'InfoOutline',
  'Warning',
  'WarningAmber',
  'Error',
  'ErrorOutline',
  'ReportProblem',
  'Help',
  'HelpOutline',
  'HelpCenter',
  'Lightbulb',
  'LightbulbOutline',
  'NewReleases',
  'Verified',
  'VerifiedUser',
  'GppGood',
  'PriorityHigh',
  'Block',
  'DoNotDisturb',
  'CircleNotifications',
  'Pending',
  'HourglassEmpty',
  'HourglassFull',
  'Schedule',
  'AccessTime',
  'Timer',
  'WatchLater',
  'Event',
  'EventAvailable',
  'EventBusy',
  'EventNote',
  'CalendarToday',
  'CalendarMonth',
  'DateRange',
  'Today',

  // Toggles / settings
  'Settings',
  'SettingsApplications',
  'SettingsSuggest',
  'Build',
  'Construction',
  'Handyman',
  'Lock',
  'LockOpen',
  'LockOutline',
  'NoEncryption',
  'Key',
  'VpnKey',
  'Password',
  'Visibility',
  'VisibilityOff',
  'Security',
  'Shield',
  'Fingerprint',
  'PowerSettingsNew',
  'ToggleOn',
  'ToggleOff',
  'LightMode',
  'DarkMode',
  'SettingsBrightness',
  'Brightness4',
  'Brightness7',
  'Contrast',
  'Palette',
  'ColorLens',
  'FormatPaint',
  'Brush',

  // Media controls
  'PlayArrow',
  'Pause',
  'Stop',
  'SkipNext',
  'SkipPrevious',
  'FastForward',
  'FastRewind',
  'Replay',
  'VolumeUp',
  'VolumeDown',
  'VolumeMute',
  'VolumeOff',
  'Mic',
  'MicOff',
  'Videocam',
  'VideocamOff',
  'PhotoCamera',
  'Camera',
  'CameraAlt',
  'MusicNote',
  'LibraryMusic',
  'QueueMusic',
  'PlaylistAdd',
  'PlaylistPlay',

  // Commerce
  'ShoppingCart',
  'ShoppingCartCheckout',
  'AddShoppingCart',
  'RemoveShoppingCart',
  'ShoppingBag',
  'Store',
  'Storefront',
  'LocalMall',
  'LocalOffer',
  'Sell',
  'Payment',
  'CreditCard',
  'AccountBalance',
  'AccountBalanceWallet',
  'AttachMoney',
  'MonetizationOn',
  'Receipt',
  'ReceiptLong',
  'Discount',

  // Ratings / social
  'Star',
  'StarBorder',
  'StarHalf',
  'StarOutline',
  'Favorite',
  'FavoriteBorder',
  'ThumbUp',
  'ThumbDown',
  'ThumbUpOffAlt',
  'ThumbDownOffAlt',
  'Grade',
  'EmojiEvents',
  'Mood',
  'MoodBad',
  'SentimentSatisfied',
  'SentimentDissatisfied',

  // Maps / places
  'Place',
  'LocationOn',
  'LocationOff',
  'MyLocation',
  'Map',
  'Explore',
  'Navigation',
  'NearMe',
  'Directions',
  'Flag',
  'OutlinedFlag',
  'Public',
  'Language',
  'Translate',

  // Devices / tech
  'Computer',
  'Laptop',
  'DesktopWindows',
  'PhoneIphone',
  'PhoneAndroid',
  'Tablet',
  'TabletMac',
  'Watch',
  'Tv',
  'Devices',
  'DeviceHub',
  'Keyboard',
  'Mouse',
  'Memory',
  'Storage',
  'Router',
  'Wifi',
  'WifiOff',
  'Bluetooth',
  'BluetoothDisabled',
  'BatteryFull',
  'BatteryChargingFull',
  'SignalCellular4Bar',
  'NetworkCheck',

  // Misc objects
  'Dashboard',
  'BarChart',
  'PieChart',
  'ShowChart',
  'TrendingUp',
  'TrendingDown',
  'TrendingFlat',
  'Insights',
  'Analytics',
  'Assessment',
  'Timeline',
  'Leaderboard',
  'QueryStats',
  'TableChart',
  'CalendarViewMonth',
  'CheckList',
  'List',
  'ListAlt',
  'FormatListBulleted',
  'FormatListNumbered',
  'Toc',
  'Layers',
  'LayersClear',
  'Category',
  'Inventory',
  'Inventory2',
  'Archive',
  'Unarchive',
  'Backup',
  'RestoreFromTrash',

  // Text formatting
  'FormatBold',
  'FormatItalic',
  'FormatUnderlined',
  'FormatStrikethrough',
  'FormatColorText',
  'FormatColorFill',
  'FormatAlignLeft',
  'FormatAlignCenter',
  'FormatAlignRight',
  'FormatAlignJustify',
  'FormatIndentIncrease',
  'FormatIndentDecrease',
  'FormatQuote',
  'FormatSize',
  'TextFields',
  'Title',
  'TextFormat',

  // Weather / nature
  'WbSunny',
  'WbCloudy',
  'Cloud',
  'CloudQueue',
  'Thunderstorm',
  'AcUnit',
  'Whatshot',
  'LocalFireDepartment',
  'Water',
  'WaterDrop',
  'Air',
  'Park',
  'Forest',
  'Pets',

  // Transport
  'DirectionsCar',
  'DirectionsBus',
  'DirectionsBike',
  'DirectionsWalk',
  'DirectionsRun',
  'Flight',
  'FlightTakeoff',
  'FlightLand',
  'Train',
  'Subway',
  'LocalShipping',
  'LocalTaxi',
  'TwoWheeler',
  'ElectricCar',

  // Health / food
  'Favorite',
  'MonitorHeart',
  'MedicalServices',
  'LocalHospital',
  'Medication',
  'Vaccines',
  'Restaurant',
  'RestaurantMenu',
  'LocalCafe',
  'LocalBar',
  'Fastfood',
  'Cake',
  'EmojiFoodBeverage',

  // Generic shapes / symbols
  'Circle',
  'Square',
  'RectangleOutlined',
  'Pentagon',
  'Hexagon',
  'ChangeHistory',
  'Star',
  'Bolt',
  'FlashOn',
  'FlashOff',
  'Power',
  'PowerOff',
  'Cable',
  'Hub',
  'AccountTree',
  'Schema',
  'Polyline',
  'Gesture',
  'TouchApp',
  'PanTool',
  'BackHand',
  'Adjust',
  'Brightness1',
  'FiberManualRecord',
  'Lens',
  'CropSquare',
  'CropDin',
  'CropFree',
  'Crop',
  'AspectRatio',
  'PhotoSizeSelectActual',
  'Wallpaper',
  'GridOn',
  'GridOff',
  'BorderAll',
  'BorderClear',
  'Tab',
  'TabUnselected',
  'Window',
  'SplitscreenOutlined',
  'Splitscreen',
  'VerticalSplit',
  'HorizontalSplit',
]);

// De-duplicate (the curated source above intentionally repeats some popular
// names across category groupings for readability) and keep a stable order.
const seen = new Set();
/** @type {string[]} */
const deduped = [];
for (const name of ICON_NAMES) {
  if (!seen.has(name)) {
    seen.add(name);
    deduped.push(name);
  }
}

/**
 * The curated, de-duplicated list of suggestable Material icon names.
 * @type {readonly string[]}
 */
export const iconNames = Object.freeze(deduped);

export default iconNames;
